### ISSUE TITLE
Enhancment: Better handling of edge cases in Dijkstra’s Algorithm

### ISSUE THREAD

**Issue by houssamallali** [anshumansinha3301/Dijkstra-in-python#1]
The current Dijkstra’s algorithm code works, but it could be improved to handle some extra edge cases and maybe have clearer errors. Here’s a couple of ideas:

	1.	Disconnected Nodes:
	•	Right now, the code doesn’t really handle nodes that are disconnected from the start node. This could be confusing if a user gets results without knowing which nodes aren’t reachable.
	2.	Negative Weights:
	•	Dijkstra’s algorithm only works with positive weights, but this code doesn’t check for that. Adding a check to make sure all weights are positive could prevent problems if a graph with negative weights is used by mistake.

Suggested Fixes:

	•	Add some checks in the dijkstra function to:
	•	Detect Negative Weights: If there’s a negative weight, return an error or warning.
	•	Disconnected Nodes: Make sure distances for nodes that can’t be reached from the start node are set to infinity in the output.

**Suggested Code**:
```python
import heapq

def dijkstra(graph, start):
    # Check for negative weights in the graph
    for vertex, edges in graph.items():
        for neighbor, weight in edges.items():
            if weight < 0:
                raise ValueError("Graph contains a negative weight. Dijkstra's algorithm requires all weights to be non-negative.")

    queue = []  
    heapq.heappush(queue, (0, start))

    distances = {vertex: float('infinity') for vertex in graph}   
    distances[start] = 0

    path = {vertex: None for vertex in graph}

    while queue:
        current_distance, current_vertex = heapq.heappop(queue)

        if current_distance > distances[current_vertex]:
            continue

        for neighbor, weight in graph[current_vertex].items():
            distance = current_distance + weight

            if distance < distances[neighbor]:
                distances[neighbor] = distance
                path[neighbor] = current_vertex
                heapq.heappush(queue, (distance, neighbor))

    return distances, path

**Comment by anshumansinha3301** [comment]
Thanks a lot! Adding your code as a separate code in same repository.
